resources:
- name: 1-click
  type: git
  source:
    uri: https://github.com/petergtz/1-click-bosh-lite-pipeline.git

- name: state-repo
  type: git
  source:
    # TODO Grab via spruce
    uri: &state-repo-uri git@github.com:cloudfoundry/bits-service-private-config.git
    branch: master
    private_key: {{github-private-key}}
    disable_ci_skip: true

- name: cf-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment.git

- name: cf-smoke-tests
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-smoke-tests.git

- name: boshlite-stemcell
  type: bosh-io-stemcell
  source: { name: bosh-warden-boshlite-ubuntu-trusty-go_agent}

- name: (( concat meta.bosh-lite-name "-recreation-events" ))
  type: semver
  source:
    driver: git
    uri: (( grab meta.events-git-repo ))
    branch: events
    file: (( concat "events-bosh-lites-" meta.bosh-lite-name "-created" ))
    private_key: {{github-private-key}}

- name: (( concat meta.bosh-lite-name "-cf-deployment-events" ))
  type: semver
  source:
    driver: git
    uri:  (( grab meta.events-git-repo ))
    branch: events
    file: (( concat "events-bosh-lites-" meta.bosh-lite-name "-deployments-cf-deleted" ))
    private_key: {{github-private-key}}

- name: every-night
  type: time
  source:
    start: 1:00 AM
    stop: 2:00 AM

jobs:
- name: (( concat "delete-" meta.bosh-lite-name ))
  serial: true
  plan:
  - aggregate:
    - get: 1-click
    - get: (( concat meta.bosh-lite-name "-recreation-events" ))
      params: { bump: major }
    - get: state-repo
  - task: bosh delete-env
    file: 1-click/tasks/bosh-delete-env.yml
    input_mapping:
      state: state-repo
    params:
      BOSH_LITE_NAME: (( grab meta.bosh-lite-name ))
      MANIFEST: {{bosh-manifest}}
  - put: state-repo
    params:
      repository: out-state
  - put: (( concat meta.bosh-lite-name "-recreation-events" ))
    params:
      file: (( concat meta.bosh-lite-name "-recreation-events/number" ))

- name: (( concat "recreate-" meta.bosh-lite-name ))
  serial: true
  plan:
  - aggregate:
    - get: 1-click
    - get: (( concat meta.bosh-lite-name "-recreation-events" ))
      params: { bump: major }
      trigger: true
      passed: [ (( concat "delete-" meta.bosh-lite-name )) ]
    - get: state-repo
  - task: bosh create-env
    file: 1-click/tasks/bosh-create-env.yml
    input_mapping:
      # TODO Is this used anywhere?
      manifest-dir: state-repo
      state: state-repo
    params:
      BOSH_LITE_NAME: (( grab meta.bosh-lite-name ))
      MANIFEST: {{bosh-manifest}}
  - put: state-repo
    params:
      repository: out-state
  - put: (( concat meta.bosh-lite-name "-recreation-events" ))
    params:
      file: (( concat meta.bosh-lite-name "-recreation-events/number" ))

- name: (( concat "update-cloud-config-" meta.bosh-lite-name ))
  plan:
  - aggregate:
    - get: (( concat meta.bosh-lite-name "-recreation-events" ))
      trigger: true
      passed: [(( concat "recreate-" meta.bosh-lite-name ))]
    - { get: 1-click }
    - { get: cf-deployment, trigger: true }
    - get: state-repo
  - task: Update cloud-config
    file: 1-click/tasks/update-cloud-config.yml
    input_mapping:
      cf-deployment: cf-deployment
      state: state-repo
    params:
      BOSH_LITE_NAME: (( grab meta.bosh-lite-name ))

- name: (( concat "delete-" meta.bosh-lite-name "-cf-deployment" ))
  serial: true
  plan:
  - aggregate:
    - get: 1-click
    - get: (( concat meta.bosh-lite-name "-cf-deployment-events" ))
      params: { bump: major }
      trigger: true
    - get: state-repo
  - task: delete-deployment
    file: 1-click/tasks/bosh-delete-deployment.yml
    input_mapping:
      state: state-repo
    params:
      DEPLOYMENT_NAME: cf
      BOSH_LITE_NAME: (( grab meta.bosh-lite-name ))
  - put: (( concat meta.bosh-lite-name "-cf-deployment-events" ))
    params:
      file: (( concat meta.bosh-lite-name "-cf-deployment-events/number" ))

- name: (( concat "deploy-cf-in-" meta.bosh-lite-name ))
  serial: true
  plan:
  - aggregate:
    - get: 1-click
    - get: (( concat meta.bosh-lite-name "-cf-deployment-events" ))
      trigger: true
    - get: (( concat meta.bosh-lite-name "-recreation-events" ))
      trigger: true
      passed: [ (( concat "update-cloud-config-" meta.bosh-lite-name )) ]
    - get: state-repo
    - get: cf-deployment
    - { get: stemcell, resource: boshlite-stemcell, version: {version: "3468.19"} }
  - task: Generate cf deployment manifest
    file: 1-click/tasks/generate-cf-deployment-manifest.yml
    input_mapping:
      state: state-repo
    output_mapping:
      out: manifest
    params:
      BOSH_LITE_NAME: (( grab meta.bosh-lite-name ))
      CF_SYSTEM_DOMAIN: (( grab meta.cf-system-domain ))
  - aggregate:
    - put: state-repo
      params:
        repository: out-state
    - task: Deploy cf
      file: 1-click/tasks/bosh-deploy.yml
      params:
        BOSH_LITE_NAME: (( grab meta.bosh-lite-name ))
      input_mapping:
        state: state-repo
  # TODO: Do we want to keep this here? This task makes the pipline less generally useful.
  - task: Update changeip.com
    file: 1-click/tasks/update-changeip-dns.yml
    input_mapping:
      state: state-repo
    params:
      BOSH_LITE_NAME: (( grab meta.bosh-lite-name ))
      CHANGE_IP_USER: {{changeip-username}}
      CHANGE_IP_PASSWORD: {{changeip-password}}
      CF_SYSTEM_DOMAIN: (( grab meta.cf-system-domain ))

- name:  (( concat "run-cf-smoke-tests-in-" meta.bosh-lite-name ))
  serial: true
  plan:
  - aggregate:
    - get: 1-click
    - get: (( concat meta.bosh-lite-name "-cf-deployment-events" ))
      passed: [ (( concat "deploy-cf-in-" meta.bosh-lite-name )) ]
      trigger: true
    - get: (( concat meta.bosh-lite-name "-recreation-events" ))
      trigger: true
      passed: [ (( concat "deploy-cf-in-" meta.bosh-lite-name )) ]
    - get: state-repo
    - get: cf-smoke-tests
  - task: Run smoke-tests
    file: 1-click/tasks/run-smoke-tests.yml
    params:
      BOSH_LITE_NAME: (( grab meta.bosh-lite-name ))
      CF_SYSTEM_DOMAIN: (( grab meta.cf-system-domain ))
    input_mapping:
      state: state-repo

- name: (( concat "clean-up-" meta.bosh-lite-name ))
  serial: true
  plan:
  - aggregate:
    - { get: 1-click }
    - { get: every-night, trigger: true }
    - get: state-repo
  - task: bosh clean-up
    file: 1-click/tasks/bosh-clean-up.yml
    input_mapping:
      state: state-repo
    params:
      BOSH_LITE_NAME: (( grab meta.bosh-lite-name ))

- name: (( concat "cancel-cf-deployment-task-in-" meta.bosh-lite-name ))
  serial: true
  plan:
  - aggregate:
    - { get: 1-click }
    - get: state-repo
  - task: bosh -d cf cancel-task
    file: 1-click/tasks/bosh-cancel-task.yml
    input_mapping:
      state: state-repo
    params:
      BOSH_LITE_NAME: (( grab meta.bosh-lite-name ))
      DEPLOYMENT_NAME: cf

- name: (( concat "show-summary-" meta.bosh-lite-name ))
  plan:
  - task: Show Summary
    file: 1-click/tasks/show-summary.yml
    input_mapping:
      state: state-repo
    params:
      BOSH_LITE_NAME: (( grab meta.bosh-lite-name ))
      CF_SYSTEM_DOMAIN: (( grab meta.cf-system-domain ))
      STATE_REPO_URI: *state-repo-uri
