resources:
- name: 1-click
  type: git
  source:
    uri: https://github.com/petergtz/1-click-bosh-lite-pipeline.git

- name: state
  type: git
  source:
    uri: (( grab meta.state-git-repo ))
    branch: master
    private_key: {{github-private-key}}
    disable_ci_skip: true

- name: cf-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment.git

- name: (( concat meta.bosh-lite-name "-recreation-events" ))
  type: semver
  source:
    driver: git
    uri: (( grab meta.state-git-repo ))
    branch: events
    file: (( concat "events-bosh-lites-" meta.bosh-lite-name "-created" ))
    private_key: {{github-private-key}}

- name: (( concat meta.bosh-lite-name "-cf-deployment-events" ))
  type: semver
  source:
    driver: git
    uri:  (( grab meta.state-git-repo ))
    branch: events
    file: (( concat "events-bosh-lites-" meta.bosh-lite-name "-deployments-cf-deleted" ))
    private_key: {{github-private-key}}

- name: every-night
  type: time
  source:
    start: 1:00 AM
    stop: 2:00 AM

jobs:
- name: (( concat "delete-" meta.bosh-lite-name ))
  serial: true
  plan:
  - aggregate:
    - get: 1-click
    - get: (( concat meta.bosh-lite-name "-recreation-events" ))
      params: { bump: major }
    - get: state
  - task: bosh delete-env
    file: 1-click/tasks/bosh-delete-env.yml
    params:
      BOSH_LITE_NAME: (( grab meta.bosh-lite-name ))
      MANIFEST: {{bosh-manifest}}
  - put: state
    params:
      repository: out-state
      rebase: true
  - put: (( concat meta.bosh-lite-name "-recreation-events" ))
    params:
      file: (( concat meta.bosh-lite-name "-recreation-events/number" ))

- name: (( concat "recreate-" meta.bosh-lite-name ))
  serial: true
  plan:
  - aggregate:
    - get: 1-click
    - get: (( concat meta.bosh-lite-name "-recreation-events" ))
      params: { bump: major }
      trigger: true
      passed: [ (( concat "delete-" meta.bosh-lite-name )) ]
    - get: state
  - task: bosh create-env
    file: 1-click/tasks/bosh-create-env.yml
    input_mapping:
      # TODO Is this used anywhere?
      manifest-dir: state
    params:
      BOSH_LITE_NAME: (( grab meta.bosh-lite-name ))
      MANIFEST: {{bosh-manifest}}
  - put: state
    params:
      repository: out-state
      rebase: true
  - put: (( concat meta.bosh-lite-name "-recreation-events" ))
    params:
      file: (( concat meta.bosh-lite-name "-recreation-events/number" ))

- name: (( concat "Show BOSH summary for " meta.bosh-lite-name ))
  plan:
  - aggregate:
    - { get: 1-click }
    - get: state
    - get: (( concat meta.bosh-lite-name "-recreation-events" ))
      trigger: true
      passed: [ (( concat "recreate-" meta.bosh-lite-name )) ]
  - task: Show Summary
    file: 1-click/tasks/show-summary.yml
    params:
      BOSH_LITE_NAME: (( grab meta.bosh-lite-name ))

- name: (( concat "update-cloud-config-" meta.bosh-lite-name ))
  plan:
  - aggregate:
    - get: (( concat meta.bosh-lite-name "-recreation-events" ))
      trigger: true
      passed: [(( concat "recreate-" meta.bosh-lite-name ))]
    - { get: 1-click }
    - { get: cf-deployment, trigger: true }
    - get: state
  - task: Update cloud-config
    file: 1-click/tasks/update-cloud-config.yml
    input_mapping:
      cf-deployment: cf-deployment
    params:
      BOSH_LITE_NAME: (( grab meta.bosh-lite-name ))

- name: (( concat "delete-" meta.bosh-lite-name "-cf-deployment" ))
  serial: true
  plan:
  - aggregate:
    - get: 1-click
    - get: (( concat meta.bosh-lite-name "-cf-deployment-events" ))
      params: { bump: major }
    - get: state
  - task: delete-deployment
    file: 1-click/tasks/bosh-delete-deployment.yml
    params:
      DEPLOYMENT_NAME: cf
      BOSH_LITE_NAME: (( grab meta.bosh-lite-name ))
  - put: (( concat meta.bosh-lite-name "-cf-deployment-events" ))
    params:
      file: (( concat meta.bosh-lite-name "-cf-deployment-events/number" ))

- name: (( concat "clean-up-" meta.bosh-lite-name ))
  serial: true
  plan:
  - aggregate:
    - { get: 1-click }
    - { get: every-night, trigger: true }
    - get: state
  - task: bosh clean-up
    file: 1-click/tasks/bosh-clean-up.yml
    params:
      BOSH_LITE_NAME: (( grab meta.bosh-lite-name ))

- name: (( concat "cancel-cf-deployment-task-in-" meta.bosh-lite-name ))
  serial: true
  plan:
  - aggregate:
    - { get: 1-click }
    - get: state
  - task: bosh -d cf cancel-task
    file: 1-click/tasks/bosh-cancel-task.yml
    params:
      BOSH_LITE_NAME: (( grab meta.bosh-lite-name ))
      DEPLOYMENT_NAME: cf

