---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
  - name: manifest-dir
  - name: state
  - name: 1-click
outputs:
  - name: out-state

params:
  BOSH_LITE_NAME: unconfigured
  MANIFEST: unconfigured

run:
  path: 1-click/tasks/bosh-create-env.sh
