---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
  - name: stemcell
  - name: 1-click
  - name: state
  - name: manifest

params:
  BOSH_LITE_NAME: unconfigured

run:
  path: 1-click/tasks/bosh-deploy.sh
