---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
  - name: cf-deployment
  - name: state
  - name: 1-click
outputs:
  - name: out-state

params:
  BOSH_LITE_NAME: unconfigured
  CF_SYSTEM_DOMAIN: unconfigured

run:
  path: 1-click/tasks/generate-cf-deployment-manifest.sh

