---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
  - name: 1-click
  - name: state

params:
  BOSH_LITE_NAME: unconfigured
  CF_SYSTEM_DOMAIN: unconfigured

run:
  path: 1-click/tasks/show-cf-summary.sh
