---
platform: linux

image_resource: { type: docker-image, source: { repository: flintstonecf/ci } }

inputs:
  - name: cf-deployment
  - name: 1-click
  - name: state

params:
  BOSH_LITE_NAME: unconfigured

run:
  path: 1-click/tasks/update-cloud-config.sh
